orbs:
  node: circleci/node@4.2.1

version: 2.1
workflows:
  conditional-workflow:
    when:
      conditional:
        - equal: [ master, << pipeline.git.branch >> ]
      jobs:
        - node/test
    jobs:
        - node/test