orbs:
  node: circleci/node@4.2.1

version: 2.1
steps:
  - run:
      name: Setup Environment Variables
      command: |
        echo $DEPLOY_STATE_FREEZE
workflows:
  app-tests:
    when:  
      condition:
        equal: [ true, $DEPLOY_STATE_FREEZE ]
      jobs:
        - node/test
