orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  test:
    docker: # executor type
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:  | 
          commit_message= $DEPLOY_STATE_FREEZE_V4
          if [[ $commit_message == *"custom-identifier"* ]]; then
          curl --request POST \
            --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
            --header "Circle-Token: 03b11f8892726564c1ab3d8d2d5a18c34107314e"
          fi
workflows:
  integration_tests:
    jobs:
      - test
      - node/test
    # when: 
    #   condition:
    #     equal: [ true, "${<< parameters.condition_needed >>}" ]
       