orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
  test:
    docker: # executor type
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:  | 
          TEST_VAR=$(curl https://winston-staging.syllable.ai)
          echo ${TEST_VAR}
      - run:
          name: "Print an env var stored in a ContextSSS1"
          command: echo ${TEST_VAR}
workflows:
  integration_tests:
    jobs:
      - test
      - node/test
    # when: 
    #   condition:
    #     equal: [ true, "${<< parameters.condition_needed >>}" ]
       