orbs:
  node: circleci/node@4.2.1

version: 2.1
workflows:
  integration_tests:
    jobs:
      - checkout
      - run: | 
          if [[ DEPLOY_STATE_FREEZE_V3 == *"true"* ]]; then
          curl --request POST \
            --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel \
            --header "Circle-Token: 03b11f8892726564c1ab3d8d2d5a18c34107314e"
          fi
      - node/test
    # when: 
    #   condition:
    #     equal: [ true, "${<< parameters.condition_needed >>}" ]
       