orbs:
  node: circleci/node@4.2.1

version: 2.1
parameters:
  condition_needed:
    default: DEPLOY_STATE_FREEZE_V3
    type: env_var_name

workflows:
  integration_tests:
    when: 
      condition:
        equal: [ true, "${<< parameters.condition_needed >>}" ]
    jobs:
        - node/test