orbs:
  node: circleci/node@4.2.1

version: 2.1
parameters:
  workingdir:
    type: boolean
    default: true
steps:
  - run:
      name: Setup Environment Variables
      command: |
        echo $DEPLOY_STATE_FREEZE
workflows:
  app-tests:
    when:  
      condition:
        equal: [ true, "<< pipeline.parameters.workingdir >>"]
      jobs:
        - node/test
    run: echo 0
