orbs:
  node: circleci/node@4.2.1

version: 2.1
parameters:
  run_integration_tests:
    type: boolean
    default: false

workflows:
  integration_tests:
    when: false
    jobs:
        - node/test