orbs:
  node: circleci/node@4.2.1

version: 2.1
parameters:
  run_integration_tests:
    type: boolean
    default: $DEPLOY_STATE_FREEZE

workflows:
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
        - node/test